CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP,
    modifier_user varchar(255),
    valid BOOLEAN NOT NULL DEFAULT TRUE,

    name varchar(100) NOT NULL,
    username varchar(100) NOT NULL,
    password varchar(20),
    admin BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_manufacturer PRIMARY KEY (id),
    CONSTRAINT uk_username UNIQUE KEY (username)
);