apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ms-auth"
  template:
    metadata:
      name: ms-auth
      labels:
        app: "ms-auth"
    spec:
      containers:
      - name: ms-auth
        image: ms-auth:v1.0.0
        env:
          - name: DATABASE_URL
            value: "192.168.0.7"
        ports:
          - containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: "ms-auth"
spec:
  selector:
    app: "ms-auth"
  ports:
  - name: "application-port"
    port: 5000
    targetPort: 5000